language: php

php:
  - 5.4
  - 5.5
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

notifications:
  email: false
  slack:
    secure: uRTGIDjw1j6QYsz7CQ5uQBZO4SyeeJ5lBjoJFx4QQZwCLd1uAYE2erRSLu00yLXNDxs4pup//z2ThzWmQlfd682EYMBPoscnA/pwxztirsxQdbC04/zjLoXe8oMUCOG6i575ZNUKBHXRGirGbIbwb9sMitzyx0vmEgZd7h9STfI=

before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database `harp-orm/materialized-path`;'
  - mysql harp-orm/materialized-path < tests/mysql.sql

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - test -e build/logs/clover.xml && wget https://scrutinizer-ci.com/ocular.phar
  - test -e build/logs/clover.xml && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
